### ISSUE TITLE
bug: Melos at_onboarding_cli / at_onboarding_flutter conflict

### ISSUE THREAD

**Issue by xavierchanth** [atsign-foundation/at_mono#33]
### Describe the bug

Working through fixing at_mono and I'm noticing something very weird with our dependencies...

Melos is telling me that at_app_flutter depends on both at_onboarding_cli and at_onboarding_flutter:

```
Because every version of at_onboarding_flutter from path depends on zxing2 ^0.1.0 and every version of at_onboarding_cli from path depends on zxing2 ^0.2.0, at_onboarding_flutter from path is incompatible with at_onboarding_cli from path.
So, because at_app_flutter depends on both at_onboarding_cli from path and at_onboarding_flutter from path, version solving failed.
BootstrapException: Failed to install.: at_app_flutter at /Users/chant/src/af/at_mono/modules/at_app/packages/at_app_flutter.
```

Here are all of the dependencies:

```yaml
dependencies:
  flutter:
    sdk: flutter
  at_onboarding_flutter: ">=4.0.0 <7.0.0"
  at_utils: ^3.0.5
  flutter_dotenv: ^5.0.2
  meta: ^1.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  lints: ">=1.0.0 <3.0.0"
  mockito: ^5.1.0
```
The interesting thing is that at_onboarding_cli has no dependents, so I think that there is a bug in melos...
https://pub.dev/packages?q=dependency:at_onboarding_cli

### Steps to reproduce

1. First I '...'
2. Then I '...'
3. And then '...'
4.

### Expected behavior

N/A

### Additional context

I will look at options to solve this issue, and check for issues filed against melos.
I think the best option for now is to:

1. force a dependency constraint
2. update onboarding_cli/onboarding_flutter to use the same versions
3. Remove onboarding_cli from at_mono temporarily
